import { createSlice } from '@reduxjs/toolkit';

const initialState = {
	levels: [
		{
			id: 5,
			name: 'Superintendent Membership',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 98,
			fee: 0,
			level: 1,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'individual_member',
		},
		{
			id: 6,
			name: 'Deputy Superintendent Membership',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 80,
			fee: 0,
			level: 1,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'individual_member',
		},
		{
			id: 10,
			name: 'Associate Membership',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 80,
			fee: 0,
			level: 1,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'individual_member',
		},
		{
			id: 11,
			name: 'Groundsman Membership',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 80,
			fee: 0,
			level: 1,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'individual_member',
		},
		{
			id: 7,
			name: 'Greenkeeper Membership',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 70,
			fee: 0,
			level: 1,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'individual_member',
		},
		{
			id: 9,
			name: 'Retired Membership',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 60,
			fee: 0,
			level: 1,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'individual_member',
		},
		{
			id: 8,
			name: 'Apprentice/ Student Membership',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 60,
			fee: 0,
			level: 1,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'individual_member',
		},
		{
			id: 3,
			name: 'Club Membership',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 350,
			fee: 0,
			level: 3,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'club_owner',
		},
		{
			id: 4,
			name: 'Club Member',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 0,
			fee: 0,
			level: 2,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'club_member',
		},
		{
			id: 2,
			name: 'Individual Member',
			duration: 1,
			renewal_date: '27/06/2022',
			price: 0,
			fee: 0,
			level: 1,
			currency_symbol: 'EUR',
			duration_unit: 'month',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'subscriber',
		},
		{
			id: 12,
			name: 'Club included members',
			duration: 1,
			renewal_date: '27/05/2023',
			price: 0,
			fee: 0,
			level: 0,
			currency_symbol: 'EUR',
			duration_unit: 'year',
			trial_duration: 0,
			trial_duration_unit: 'day',
			maximum_renewals: 0,
			role: 'club_member',
		},
	],
};

const levelsSlice = createSlice({
	name: 'levels',
	initialState,
	reducers: {
		setMembershipLevels: (state, { payload }) => {
			state.levels = payload;
		},
	},
});

export const { setMembershipLevels } = levelsSlice.actions;

export const selectMembershipLevels = state => state.levels;

export default levelsSlice.reducer;
